before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - sudo service docker stop
  - sudo dockerd --experimental &
  - docker version
  - docker build -t beeglercorp --compress --force-rm --no-cache --squash .

# skip the install step
# @see https://docs.travis-ci.com/user/customizing-the-build/#Skipping-the-Installation-Step
install: true

language: node_js

script:
- |
  DOCKER_SIZE_STRING="$(docker images beeglercorp --format {{.Size}})"
  DOCKER_SIZE_NUMBER=${DOCKER_SIZE_STRING%MB}

  echo $DOCKER_SIZE_STRING

  if [ ${#DOCKER_SIZE_STRING} -eq ${#DOCKER_SIZE_NUMBER} ]; then
    # the size is not in MB, we're going to assume it's in something greater than MB
    # since no Docker image <1MB exists to-date
    echo "Size >999MB."
    exit 1
  fi

  DOCKER_SIZE_ROUNDED="$(echo $DOCKER_SIZE_NUMBER | awk '{print int($1+0.9)}')"

  if [ 45 -gt $DOCKER_SIZE_ROUNDED ]; then
    echo "Ok"
    exit 0
  else
    echo "Fail"
    exit 1
  fi

services:
  - docker

sudo: required
