before_install:
  - docker build -t beeglercorp .

# skip the install step
# @see https://docs.travis-ci.com/user/customizing-the-build/#Skipping-the-Installation-Step
install: true

language: node_js

script: docker images

services:
  - docker

sudo: required
